version: '3.8'

services:
  client: 
    build: 
      context: ./client
    hostname: nodejsserver
    ports:
      - "3000:3000" 
    networks:
      - dev
  
  nginx:
    build:
      context: ./nginx
    depends_on:
      - client
    ports: 
      - "80:80"
    networks:
      - dev

networks:
  dev:
    driver: bridge


